sudo: required
services:
  - docker

before_install:
  - docker build -t dboadudev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dboadudev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: "website"
  env: "Website-env"
  bucket_name: "elasticbeanstalk-us-east-1-870924474671"
  bucket_path: "website"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
